apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-php
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-php
          image: demo-php:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9000
        - name: demo-nginx
          image: demo-nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 150m
            requests:
              cpu: 50m
